apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: ditt-nav-arbeidsgiver-api-alert
  labels:
    team: teamtag
spec:
  receivers:
    slack:
      channel: 'tag-notifications'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: count(kube_pod_container_status_running{container="ditt-nav-arbeidsgiver-api"}) == 0
      for: 2m
      description: "ditt-nav-arbeidsgiver er nede i prod"
      action: "finn podden i kubectl og undersøk loggene for å finne feilen"
    - alert: høy feilrate i logger
      expr: logback_events_total{level="error", app="ditt-nav-arbeidsgiver-api"}>0
      for: 3m
      action: "Sjekk loggene til ditt-nav-arbeidsgiver, for å se hvorfor det er så mye feil"