apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-nav-arbeidsgiver-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/ditt-nav-arbeidsgiver-api:5ceb7fd8162cf2c36f81f2b0013526eb17d61805
  team: teamtag
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/ditt-nav-arbeidsgiver-api/
  vault:
    enabled: true
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/health
    initialDelay: 30
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
