apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-nav-arbeidsgiver-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/ditt-nav-arbeidsgiver-api:latest
  team: teamtag
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/ditt-nav-arbeidsgiver-api/
  vault:
    enabled: true
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/isAlive
    initialDelay: 20
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/isReady
    initialDelay: 20
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
