spring:
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /ditt-nav-arbeidsgiver-api


no.nav.security.oidc:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: http://metadata-selvbetjening
      accepted_audience: aud-selvbetjening