server:
  port: 8080
  servlet:
    context-path: /ditt-nav-arbeidsgiver-api

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

no.nav.security.oidc:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: http://metadata-selvbetjening
      accepted_audience: aud-selvbetjening

mock:
  enabled: true
  port: 8081
  aktorPort: 8082

sts:
  stsPass: "mockpass"
  stsUrl: "http://localhost:${mock.port}/sts"

aktorregister:
  aktorUrl: "http://localhost:${mock.port}/aktoerregister/api/v1/identer"

altinn:
  altinnUrl: "http://localhost:${mock.port}/altinn"
  altinnHeader: "test"
  APIGwHeader: "test"

digisyfo:
  digisyfoUrl: "http://localhost:${mock.port}/digisyfo/api/"

aad:
  aadAccessTokenURL: "https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token"
---

spring:
  profiles: preprod


digisyfo:
  digisyfoUrl: "https://syfoarbeidsgivertilgang.nais.preprod.local/api/"

sts:
  stsPass: ${STS_PASS}
  stsUrl: https://security-token-service.nais.preprod.local/rest/v1/sts/token

aktorregister:
  akotrUrl: "https://app-q1.adeo.no/aktoerregister/api/v1/identer"

aad:
  aadAccessTokenURL: "https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token"
  azureClientSecret:  ${AZURE_CLIENT_SECRET}
  clientid: 1b1bf278-3c28-4003-a528-b595d800afb0
  scope: https://trygdeetaten.no/syfoarbeidsgivertilgang/.default

no.nav.security.oidc:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
      accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5

altinn:
  altinnUrl: "https://api-gw-q1.adeo.no/ekstern/altinn/api/serviceowner/"
  altinnHeader: ${ALTINN_HEADER}
  APIGwHeader: ${APIGW_HEADER}

---

spring:
  profiles: prod

no.nav.security.oidc:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
      accepted_audience: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25

altinn:
  altinnUrl: "https://api-gw.adeo.no/ekstern/altinn/api/serviceowner/"
  altinnHeader: ${ALTINN_HEADER}
  APIGwHeader: ${APIGW_HEADER}

