version: 2.1
jobs:
  bygg:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Bygger med Maven
          command: mvn clean package
      - setup_remote_docker
      - run:
          name: Bygger Docker image
          command: docker build -t "navikt/ditt-nav-arbeidsgiver-api:$CIRCLE_SHA1" .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            docker push "navikt/ditt-nav-arbeidsgiver-api:$CIRCLE_SHA1"
            
  deploy-til-dev:
    docker:
      - image: 'navikt/deployment-cli:v0.3.0'
    steps:
      - deploy:
          cluster: "dev-fss"
          nais-yaml: "nais-preprod-fss.yaml"

  deploy-til-prod:
    docker:
      - image: 'navikt/deployment-cli:v0.3.0'
    steps:
      - deploy:
          cluster: "prod-fss"
          nais-yaml: "nais-prod-fss.yaml"

commands:
  deploy:
    description: Deploy til et gitt miljø
    parameters:
      cluster:
        type: string
      nais-yaml:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy til << parameters.cluster >>
          command: deployment-cli deploy create --cluster=<< parameters.cluster >> --repository=navikt/ditt-nav-arbeidsgiver-api --team=teamtag --resource=<< parameters.nais-yaml >> --var version=$CIRCLE_SHA1 --ref=$CIRCLE_BRANCH

workflows:
  version: 2.1
  bygg-og-deploy:
    jobs:
      - bygg:
          context: NAIS deployment
      - deploy-til-dev:
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - godkjenn-til-prod:
          type: approval
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - deploy-til-prod:
          requires:
            - godkjenn-til-prod
          filters:
            branches:
              only:
                - master