apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: ditt-nav-arbeidsgiver-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /ditt-nav-arbeidsgiver-api/internal/isAlive
    initialDelay: 70
    timeout: 15
  readiness:
    path: /ditt-nav-arbeidsgiver-api/internal/isAlive
    initialDelay: 70
    timeout: 15
  ingresses:
    - https://arbeidsgiver.dev.nav.no/ditt-nav-arbeidsgiver-api/
    - https://arbeidsgiver.dev.intern.nav.no/ditt-nav-arbeidsgiver-api/
  envFrom:
    - configmap: loginservice-idporten
    - secret: min-side-ag-secrets
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: JAVA_OPTS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  prometheus:
    enabled: true
    path: /ditt-nav-arbeidsgiver-api/internal/actuator/prometheus
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: unleash.nais.io
