apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: min-side-arbeidsgiver-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: docker.pkg.github.com/navikt/ditt-nav-arbeidsgiver-api/ditt-nav-arbeidsgiver-api:6550c14af27f10c4668121348e50c39adb7b503c
  team: arbeidsgiver
  port: 8080
  liveness:
    path: /min-side-arbeidsgiver-api/internal/actuator/health
    initialDelay: 90
    timeout: 15
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /min-side-arbeidsgiver-api/internal/actuator/health
    initialDelay: 90
    timeout: 15
  ingresses:
    - https://arbeidsgiver.dev.nav.no/min-side-arbeidsgiver-api/
  envFrom:
    - configmap: loginservice-idporten
    - secret: min-side-ag-secrets
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: JAVA_OPTS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  prometheus:
    enabled: true
    path: /min-side-arbeidsgiver-api/internal/actuator/prometheus
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: unleash.nais.io
